using UnityEngine;

/// <summary>
/// Generated by RoadBuilder — do not place manually.
/// Child of a Road object, represents one unsplit stretch between intersections.
/// </summary>
public class RoadSegment : MonoBehaviour
{
    // Set by Road.Rebuild
    [HideInInspector] public Road  ParentRoad;
    [HideInInspector] public int   SegmentIndex;
    [HideInInspector] public bool  IsLastSegment;

    // Copied from parent Road
    public RoadClass RoadClass;
    public int       LaneCountOverride;
    public bool      HasTrafficLight;
    public float     GreenDuration   = 20f;
    public float     YellowDuration  = 2f;
    public float     RedDuration     = 20f;
    public TrafficLight.State InitialState = TrafficLight.State.Green;

    // ---------------------------------------------------------------
    public int   LaneCount  => LaneCountOverride > 0 ? LaneCountOverride : RoadClassInfo.DefaultLaneCount(RoadClass);
    public int   SpeedLimit => RoadClassInfo.SpeedLimit(RoadClass);
    public float WorldLength => transform.localScale.z;
    public float WorldWidth  => transform.localScale.x;

    public Vector3 StartPosition => Flatten(transform.position - transform.forward * WorldLength * 0.5f);
    public Vector3 EndPosition   => Flatten(transform.position + transform.forward * WorldLength * 0.5f);

    public Vector3 LaneStartPosition(int laneIndex) => LaneCenterPosition(StartPosition, laneIndex);
    public Vector3 LaneEndPosition(int laneIndex)   => LaneCenterPosition(EndPosition,   laneIndex);

    Vector3 LaneCenterPosition(Vector3 faceCenter, int laneIndex)
    {
        if (LaneCount <= 1) return faceCenter;
        Vector3 right     = Vector3.Cross(Vector3.up, transform.forward).normalized;
        float   laneWidth = WorldWidth / LaneCount;
        float   offset    = (laneIndex - (LaneCount - 1) * 0.5f) * laneWidth;
        return faceCenter + right * offset;
    }

    static Vector3 Flatten(Vector3 v) => new Vector3(v.x, 0f, v.z);

    // ---------------------------------------------------------------
#if UNITY_EDITOR
    void OnDrawGizmos()
    {
        Vector3 start = StartPosition;
        Vector3 end   = EndPosition;
        Vector3 fwd   = transform.forward;
        Vector3 right = Vector3.Cross(Vector3.up, fwd).normalized;
        float   w     = WorldWidth;
        float   len   = WorldLength;

        Color roadColor = RoadClass switch
        {
            RoadClass.Highway    => new Color(0.8f, 0.2f, 0.2f, 0.35f),
            RoadClass.Arterial   => new Color(0.9f, 0.6f, 0.1f, 0.35f),
            RoadClass.Collector  => new Color(0.2f, 0.6f, 0.9f, 0.35f),
            RoadClass.Roundabout => new Color(0.2f, 0.9f, 0.5f, 0.35f),
            _                    => new Color(0.7f, 0.7f, 0.7f, 0.35f)
        };

        Gizmos.color  = roadColor;
        Gizmos.matrix = Matrix4x4.TRS(transform.position, transform.rotation, new Vector3(w, 0.05f, len));
        Gizmos.DrawCube(Vector3.zero, Vector3.one);
        Gizmos.matrix = Matrix4x4.identity;

        // Outline
        Gizmos.color = new Color(roadColor.r, roadColor.g, roadColor.b, 0.9f);
        Gizmos.DrawLine(start + right * w * 0.5f, end + right * w * 0.5f);
        Gizmos.DrawLine(start - right * w * 0.5f, end - right * w * 0.5f);
        Gizmos.DrawLine(start + right * w * 0.5f, start - right * w * 0.5f);
        Gizmos.DrawLine(end   + right * w * 0.5f, end   - right * w * 0.5f);

        // Lane dividers
        Gizmos.color = new Color(1f, 1f, 1f, 0.4f);
        float laneWidth = w / LaneCount;
        for (int i = 1; i < LaneCount; i++)
        {
            float   t  = -w * 0.5f + laneWidth * i;
            Gizmos.DrawLine(start + right * t, end + right * t);
        }

        // Direction arrow
        Gizmos.color = Color.yellow;
        Vector3 mid  = (start + end) * 0.5f;
        Gizmos.DrawRay(mid, fwd * len * 0.25f);
        Gizmos.DrawRay(mid + fwd * len * 0.25f, (Quaternion.Euler(0,  150, 0) * fwd) * len * 0.06f);
        Gizmos.DrawRay(mid + fwd * len * 0.25f, (Quaternion.Euler(0, -150, 0) * fwd) * len * 0.06f);

        // Traffic light indicator
        if (HasTrafficLight)
        {
            Gizmos.color = InitialState == TrafficLight.State.Green  ? Color.green  :
                           InitialState == TrafficLight.State.Yellow ? Color.yellow : Color.red;
            Gizmos.DrawSphere(EndPosition + Vector3.up * 0.5f, 0.3f);
        }

        // Lane labels
#if UNITY_EDITOR
        for (int i = 0; i < LaneCount; i++)
        {
            Vector3 labelPos = (LaneStartPosition(i) + LaneEndPosition(i)) * 0.5f + Vector3.up * 0.1f;
            UnityEditor.Handles.Label(labelPos, $"{name} L{i}");
        }
#endif
    }
#endif
}